
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int INT = 2;
  public static final int UMINUS = 11;
  public static final int MULT = 5;
  public static final int INT_LITERAL = 13;
  public static final int SEMI = 8;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int ID = 12;
  public static final int DIV = 6;
  public static final int ASSIGN = 7;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int LPAREN = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "ASSIGN",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "UMINUS",
  "ID",
  "INT_LITERAL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[4]=new String("MINUS");
		TT[2]=new String("INT");
		TT[11]=new String("UMINUS");
		TT[5]=new String("MULT");
		TT[13]=new String("INT_LITERAL");
		TT[8]=new String("SEMI");
		TT[0]=new String("EOF");
		TT[3]=new String("PLUS");
		TT[12]=new String("ID");
		TT[6]=new String("DIV");
		TT[7]=new String("ASSIGN");
		TT[1]=new String("error");
		TT[10]=new String("RPAREN");
		TT[9]=new String("LPAREN");
	}
public String getTT(int i){return TT[i];}
}

